# Lab 3 - Decision Theory in Machine Learning

Welcome to this week's lab on Decision Theory! This week, we are going to explore the basics of making decisions using simple and intuitive examples. Ads we have not yet started discussing neural networks, there is no need for deep knowledge in machine learning or neural networks here. We are focusing on the core principles that underlie decision-making in computational systems.

## Objectives

1. Understand the fundamentals of Decision Theory.
2. Apply Decision Theory to solve simple problems.
3. Develop the skills to implement basic decision-making systems.

## Part 1: Choosing a Vacation Destination

In this example, we will decide on a vacation destination based on various factors like cost, distance, and activities.

### Step 1: Define the Problem

Let's define the problem:
- We have 3 vacation destinations: Beach, Mountain, and City.
- Each destination is evaluated based on three criteria: cost (low, medium, high), distance (near, far), and activities (few, many).

### Step 2: Create the Decision Matrix

One approach to tackle such problems is to create a Decision Matrix! A Dcision Matrix for this problem can be created as below:

In [7]:
import pandas as pd

# Define the decision matrix
data = {
    'Cost': ['Low', 'High', 'Medium'],
    'Distance': ['Near', 'Far', 'Near'],
    'Activities': ['Many', 'Few', 'Many']
}
destinations = pd.DataFrame(data, index=['Beach', 'Mountain', 'City'])

### Step 3: Apply Decision Rules

We can create a simple scoring system for each criterion (e.g., Low Cost = 3 points, High Cost = 1 point). Then we can calculate the total score for each destination.

In [8]:
# Decision rules as functions
def cost_score(cost):
    if cost == 'Low':
        return 3
    elif cost == 'Medium':
        return 2
    else:
        return 1

def distance_score(distance):
    return 3 if distance == 'Near' else 1

def activities_score(activities):
    return 3 if activities == 'Many' else 1

### Step 4: Make a Decision

Now, we are ready to make a decision on which destination to choose based on the highest score.

In [9]:
# Calculate scores
destinations['Total Score'] = destinations.apply(lambda x: cost_score(x['Cost']) + distance_score(x['Distance']) + activities_score(x['Activities']), axis=1)

# Display the result
destinations

            Cost Distance Activities  Total Score
Beach        Low     Near       Many            9
Mountain    High      Far        Few            3
City      Medium     Near       Many            8

## Part 2: Choosing a Smartphone

Your task is to choose a smartphone based on different criteria like price, battery life, and camera quality.

Tasks
Define your criteria for selecting a smartphone.
Set up a decision matrix for different smartphone options.
Apply decision rules to score each smartphone.
Make a decision based on the highest score.
Guidelines
Think about the factors that are most important to you in a smartphone.
Be creative in defining your scoring system.

### Task 1: Criteria
Define your criteria for selecting a smartphone.

In [10]:
# Your code and/or explanation goes here

#load smartphone dataset
import pandas as pd
phones = pd.read_csv("smartphones.csv")
phones.head()

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,64,6.1,60,2,ios,12.0,12.0,0,1792,828
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,128,6.1,60,2,ios,12.0,12.0,0,1792,828
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,64,6.5,60,3,ios,12.0,12.0,0,2688,1242
3,apple,Apple iPhone 12,51999,7.4,1,bionic,6.0,3.10,NaN,0,...,64,6.1,60,2,ios,12.0,12.0,0,2532,1170
4,apple,Apple iPhone 12 (128GB),55999,7.5,1,bionic,6.0,3.10,NaN,0,...,128,6.1,60,2,ios,12.0,12.0,0,2532,1170

In [11]:
# observe the shape of the total dataset
phones.shape

(980, 22)

In [12]:
# check if there is duplicate model
phones["model"].duplicated().sum()

0

In [13]:
# see all the attributes of the smartphone
phones.columns

Index(['brand_name', 'model', 'price', 'avg_rating', '5G_or_not',
       'processor_brand', 'num_cores', 'processor_speed', 'battery_capacity',
       'fast_charging_available', 'fast_charging', 'ram_capacity',
       'internal_memory', 'screen_size', 'refresh_rate', 'num_rear_cameras',
       'os', 'primary_camera_rear', 'primary_camera_front',
       'extended_memory_available', 'resolution_height', 'resolution_width'],
      dtype='object')

In [14]:
# check data types
phones.dtypes

brand_name                    object
model                         object
price                          int64
avg_rating                   float64
5G_or_not                      int64
processor_brand               object
num_cores                    float64
processor_speed              float64
battery_capacity             float64
fast_charging_available        int64
fast_charging                float64
ram_capacity                   int64
internal_memory                int64
screen_size                  float64
refresh_rate                   int64
num_rear_cameras               int64
os                            object
primary_camera_rear          float64
primary_camera_front         float64
extended_memory_available      int64
resolution_height              int64
resolution_width               int64
dtype: object

In [15]:
phone_copy = phones
phone_copy = phone_copy.loc[:,["price","avg_rating","num_cores","processor_speed","battery_capacity","fast_charging","ram_capacity",
                            "internal_memory","screen_size","refresh_rate","num_rear_cameras","primary_camera_rear",
                             "primary_camera_front","resolution_height","resolution_width"]]
phone_copy.describe()

,price,avg_rating,num_cores,processor_speed,battery_capacity,fast_charging,ram_capacity,internal_memory,screen_size,refresh_rate,num_rear_cameras,primary_camera_rear,primary_camera_front,resolution_height,resolution_width
count,980.000000,879.000000,974.000000,938.000000,969.000000,769.000000,980.000000,980.000000,980.000000,980.000000,980.000000,980.000000,975.000000,980.000000,980.000000
mean,32520.504082,7.825825,7.772074,2.427217,4817.748194,46.126138,6.560204,141.036735,6.536765,92.256122,2.814286,50.319286,16.589744,2214.663265,1075.852041
std,39531.812669,0.740285,0.836845,0.464090,1009.540054,34.277870,2.744378,107.134516,0.349162,28.988052,0.776441,33.000968,10.876944,516.484254,290.164931
min,3499.000000,6.000000,4.000000,1.200000,1821.000000,10.000000,1.000000,8.000000,3.540000,60.000000,1.000000,2.000000,0.000000,480.000000,480.000000
25%,12999.000000,7.400000,8.000000,2.050000,4500.000000,18.000000,4.000000,64.000000,6.500000,60.000000,2.000000,24.000000,8.000000,1612.000000,1080.000000
50%,19994.500000,8.000000,8.000000,2.300000,5000.000000,33.000000,6.000000,128.000000,6.580000,90.000000,3.000000,50.000000,16.000000,2400.000000,1080.000000
75%,35491.500000,8.400000,8.000000,2.840000,5000.000000,66.000000,8.000000,128.000000,6.670000,120.000000,3.000000,64.000000,16.000000,2408.000000,1080.000000
max,650000.000000,8.900000,8.000000,3.220000,22000.000000,240.000000,18.000000,1024.000000,8.030000,240.000000,4.000000,200.000000,60.000000,3840.000000,2460.000000

In [16]:
## check unique specification for refresh rate, ram capacity, and internal memory
print(phones["refresh_rate"].unique())
print(phones["ram_capacity"].unique())
print(phones["internal_memory"].unique())

[ 60 120 144 165  90 240]
[ 4  6  8  3 12 16 18  2  1]
[  64  128  256  512 1024   32   16    8]

In [17]:
## criteria for smartphones: price, fast-charging availability, 5G Network availability, ram_capacity, processor speed,
## internal memory, screen resolution, and refresh rate

### Task 2: Decision Matrix
Set up a decision matrix for different smartphone options.

In [18]:
# Your code goes here
decision_matrix = phones.loc[:,["model","price","refresh_rate","5G_or_not","processor_speed","battery_capacity",
                               "fast_charging_available","ram_capacity","internal_memory","screen_size",
                               "resolution_height","resolution_width"]]
decision_matrix

,model,price,refresh_rate,5G_or_not,processor_speed,battery_capacity,fast_charging_available,ram_capacity,internal_memory,screen_size,resolution_height,resolution_width
0,Apple iPhone 11,38999,60,0,2.65,3110.0,0,4,64,6.10,1792,828
1,Apple iPhone 11 (128GB),46999,60,0,2.65,3110.0,0,4,128,6.10,1792,828
2,Apple iPhone 11 Pro Max,109900,60,0,2.65,3500.0,1,4,64,6.50,2688,1242
3,Apple iPhone 12,51999,60,1,3.10,NaN,0,4,64,6.10,2532,1170
4,Apple iPhone 12 (128GB),55999,60,1,3.10,NaN,0,4,128,6.10,2532,1170
...,...,...,...,...,...,...,...,...,...,...,...,...
975,Xiaomi Redmi Note 9 Pro,13999,60,0,2.30,5020.0,1,4,64,6.67,2400,1080
976,Xiaomi Redmi Note 9 Pro (4GB RAM + 128GB),14439,60,0,2.30,5020.0,1,4,128,6.67,2400,1080
977,Xiaomi Redmi Note 9 Pro Max,16490,60,0,2.30,5020.0,1,6,64,6.67,2400,1080
978,ZTE Axon 30S,19999,120,1,3.20,4200.0,1,6,128,6.90,2460,1080
979,ZTE Axon 40 Ultra 5G,61990,120,1,3.00,5000.0,1,8,128,6.80,2480,1116

### Task 3: Apply Decision Rules
Apply decision rules to score each smartphone.

In [34]:
# Your code goes here
import math  
def feature_included(dataset,col_name):
    if dataset[col_name] == 1:
        return 1
    else:
        return 0
    
def processor_speed(speed):
    if speed <= 1.8 or math.isnan(speed):
        return 0
    elif speed > 1.8 and speed <= 2.4:
        return 1
    elif speed > 2.4 and speed < 3:
        return 2
    else:
        return 3
    
def battery_life(lifespan):
    if lifespan < 2000 or math.isnan(lifespan):
        return 0
    elif lifespan >= 2000 and lifespan <= 3500:
        return 1
    elif lifespan > 3500 and lifespan <= 4500:
        return 2
    elif lifespan > 4500 and lifespan <= 5000:
        return 3
    else:
        return 4
    
def price_range(price):
    if price >= 150000 or price < 10000:
        return 0
    elif price < 150000 and price >= 50000:
        return 1
    elif price < 50000 and price >= 35000:
        return 2
    elif price < 35000 and price >= 20000:
        return 3
    elif price < 20000 and price >= 15000:
        return 4
    else:
        return 5

def ram(ram):
    if ram < 4:
        return 0
    elif ram >= 4 and ram <= 8:
        return 1
    elif ram > 8 and ram <= 16:
        return 2
    else:
        return 3
    
def refresh_rate(rate):
    if rate == 60 or rate == 90:
        return 1
    elif rate == 120 or rate == 144:
        return 2
    else:
        return 3
    
def memory_storage(memory):
    if memory <= 32:
        return 1
    elif memory <= 256:
        return 2
    else:
        return 3


def resolution(px_row,px_col,size):
    ppi = math.sqrt(px_row**2+px_col**2)/size
    if ppi < 250:
        return 0
    elif ppi < 300:
        return 1
    elif ppi < 350:
        return 2
    elif  ppi < 400:
        return 3
    elif ppi < 450:
        return 4 
    else:
        return 5

### Task 4: Final Decision
Make a decision based on the highest score.

In [35]:
# Your code goes here
# Calculate scores
decision_matrix['Total Score'] = decision_matrix.apply(lambda x: feature_included(x,'5G_or_not') + feature_included(x,'fast_charging_available') + 
                                                       processor_speed(x['processor_speed']) + battery_life(x['battery_capacity']) + price_range(x['price']) + 
                                                       ram(x['ram_capacity']) + refresh_rate(x['refresh_rate']) + memory_storage(x['internal_memory']) + 
                                                       resolution(x['resolution_height'],x['resolution_width'],x['screen_size']), axis=1)

# Display the result
final_results = decision_matrix.loc[:,["model","Total Score"]]

final_results.sort_values(by='Total Score',ascending = False)

                       model  Total Score
917        Xiaomi Redmi K60E           22
49   Asus ROG Phone 6 Pro 5G           22
262             Nokia N73 5G           22
914         Xiaomi Redmi K60           22
424              Poco F5 Pro           22
..                       ...          ...
181        Jio JioPhone Next            4
170             Itel A23 Pro            3
171                itel A23s            3
172             Itel A24 Pro            3
821                 Vivo Y25            2

[980 rows x 2 columns]

### Task 5: Evaluation and Reflection
Write your perspctive about Decision Theory. Could the given problem be solved using a different methodology? Explain your answer.

### The Decision Theory in the smartphone case gives the results of the best phone that is available (Xiaomi Redmi K60E), which is quite surprising as the promotion for this phone does not have the impact on customer preferences, compared to other brands such as Apple, Samsung. 

### For this type of problem, a mix benchmark testing and cost-benefit analysis can also be applied, as users can first filter the smartphones that are worth the money to buy, then do the technical test out of these phones to select the best performing one. That way customer can enjoy the phone by balancing between value and performance.

## Submission
Submit a link to your completed Jupyter Notebook file hosted on your private GitHub repository through the submission link in Blackboard.